name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run build
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install clippy
        run: rustup component add clippy
      - name: Run lint
        run: cargo clippy -- -D warnings
